### ISSUE TITLE
Addon does not work on private browsing

### ISSUE THREAD

**Issue by teamjin** [Lej77/bookmark-tree-for-tree-style-tab#9]
Thank you for the great addon. I want to report that it works fine on firefox except when private browsing.

**Comment by Lej77** [comment]
Hello! The reason that the addon doesn't work in private browsing is probably because you need to configure Tree Style Tab to allow private window information via their API. You can do that by opening Tree Style Tab's option page and navigating to the `Extra Features via Other Addons` section. Then you can enable the `Notify Messages from Private Windows` checkbox for this addon.

Also, I don't know if you are aware but Tree Style Tab has inbuilt support for bookmarking tree data so you might prefer to use that instead of using this addon.

**Comment by teamjin** [comment]
<img width="1378" alt="Screenshot 2022-05-01 at 20 21 36" src="https://user-images.githubusercontent.com/45741495/166161596-22a42a03-a2cc-44e9-ac65-f416a109d79f.png">

Maybe I'm missing something? I do not see a checkbox as you mentioned. I could go to Tree Syle Tab's developers but I thought it best to notify you first.

I think it is also worth mentioning that I can load bookmarks using both your extension via "Restore Tree" and Tree Style Tab via "Open All as a Tree" in private browsing but only Tree Style Tab allows me to bookmark during private browsing.

**Comment by Lej77** [comment]
So I tested how this works and apparently you currently need to have the `Bookmark Tree Data (Tree Style Tab) (Legacy)` context menu item enabled on this addon's option page.  Then the addon should register with Tree Style Tab and therefore show up in its `Extra Features` section. Note that if Tree Style Tab wasn't installed when this addon was enabled then you might need to disable and then re-enable this addon for it to correctly register with Tree Style Tab.

**Comment by teamjin** [comment]
`That did the trick. Thanks again for the addon, seriously going to change the way I browse since I am a heavy tab user (who isn't nowadays).

**Comment by Lej77** [comment]
I released an update (to version `4.2`) for this extension that fixes it so that the addon always registers with Tree Style Tab. This means that the legacy context menu item no longer affects whether the addon shows up on Tree Style Tab's option page.

I also copied some code from my `Tab Unloader for Tree Style Tab` addon to warn if privacy permissions are misconfigured (granted the addon access to private windows from Firefox but not from Tree Style Tab). Hopefully this should prevent anyone else from having this issue.
